version: '3.8'

services:
  order_service:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    ports:
      - "49156:8081"
      - "49155:8080"
    depends_on:
      - rabbitmq

  notification_service:
    build:
      context: .
      dockerfile: ./NotificationService/Dockerfile
    depends_on:
      - rabbitmq

  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "10758:8081"
    depends_on:
      - order_service
      - notification_service
 
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672

networks:
  default:
    driver: bridge